FROM ubuntu:18.04

ARG GRADLE_VERSION=gradle-5.5.1
  
ENV DEBIAN_FRONTEND=noninteractive
ENV DJANGO_SETTINGS_MODULE=website.settings
ENV C_FORCE_ROOT=true
ENV GRADLE_HOME=/opt/${GRADLE_VERSION}
ENV PATH=${GRADLE_HOME}/bin:${PATH}

WORKDIR /app

RUN apt-get update \
    && apt-get install -y git python3.6 python3-pip python3-tk \
        mysql-client libmysqlclient-dev python-mysqldb openjdk-11-jdk \
        unzip wget curl \
    && wget https://services.gradle.org/distributions/${GRADLE_VERSION}-bin.zip \
    && unzip ${GRADLE_VERSION}-bin.zip -d /opt \
    && python3 --version \
    && pip3 --version \
    && javac --version \
    && gradle --version

COPY . /app

WORKDIR /app/server/website

RUN pip3 install -r requirements.txt \ 
    && pip3 install codecov

COPY ./docker/credentials.py ./website/settings
#COPY ./docker/start.sh . 
#COPY ./docker/createadmin.py .
COPY ./docker/wait-for-it.sh . 

RUN chmod +x /app/server/website/*.sh

RUN sed s/'@localhost'/'@rabbitmq'/g ./website/settings/common.py > tmp \
    && mv tmp ./website/settings/common.py

#ENTRYPOINT ["./start.sh"]

